// Our Space - Auto-generated Configuration
// DO NOT edit this file manually - it's generated from repository secrets

window.SERVER_CONFIG = {
    githubRepo: 'inviswizard/ourspacedata',
    githubToken: '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'
};

// Configuration loaded from secrets:
// - OSW_REPO: GitHub repository (username/repo-name)
// - OSW_TOKEN: Personal Access Token with repo permissions
